id: A1C7102A1
base_file: fFF20.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:41:01.287304
  last_modified_at: 2022-06-17 11:41:01.287307
